#!/usr/bin/env bash
# Main Anarchy Linux installer script

# Read initial variables
export ANARCHY_CONFIG_FILE=/etc/anarchy.d/anarchy.conf
source "${ANARCHY_CONFIG_FILE}"
source "${translation_file}"

# Source libraries
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

main() {
    log "Started installation"

    # Run all the scripts
    run set-keyboard-layout
    run check-connection

    # Show wifi connection menu if user is not already connected to the internet
    if [[ $? -gt 0 ]]; then
        run connect-to-wifi
    fi

    #run test-connection
    run update-mirrorlist
    run install-yay
    run set-locale
    run set-timezone
    run prepare-disks
    run choose-installation-options
    run set-hostname
    run set-password
    #run set-user
    #run add-software
    #run install-base
    #run configure-system -> configure-desktop-additions
    #run add-user
    #run reboot-menu
}

# Check for root privileges
if [[ ${UID} -ne 0 ]]; then
    echo "Error: anarchy requires root privileges"
    echo "       Use: sudo anarchy"
    exit 1
fi

usage() {
    clear
    echo -e "Usage: ${color_green} anarchy [options]${color_none}"
    echo -e "${color_green}   -h | --help         ${color_yellow}Display this help message${color_none}"
    echo -e "${color_green}   -k | --keys         ${color_yellow}Update pacman keys${color_none}"
    echo -e "${color_green}   -u | --update       ${color_yellow}Update anarchy scripts${color_none}"
    echo -e ""
}

# Get options
case "$1" in
    -h|--help)
        usage
        exit 0
    ;;
    -k|--keys)
        update_keys
        exit $?
    ;;
    -u|--update)
        update_anarchy
        exit $?
    ;;
esac

main