#!/usr/bin/env bash

if "$menu_enter" ; then
    if [ "$full_user" == "" ]; then
        arch-chroot "$CHROOT_MOUNT_POINT" useradd -m -G audio,network,power,storage,optical -s "$sh" "$user" &>/dev/null &
                pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2useradd $user\Zn" load
        else
                arch-chroot "$CHROOT_MOUNT_POINT" useradd -m -G audio,network,power,storage,optical -c "$full_name" -s "$sh" "$user" &>/dev/null &
                pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2useradd $user\Zn" load
        fi

        input="$(echo "$pass_crypt" | openssl enc -aes-256-cbc -a -d -salt -pass pass:"$ssl_key")"
        (printf "$input\n$input" | arch-chroot "$CHROOT_MOUNT_POINT" passwd "$user") &> /dev/null &
        pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2passwd $user\Zn" load
        unset input
        echo "$(date -u "+%F %H:%M") : Password set: $user" >> "$log"

        if [ "$sudo_user" == "yes" ]; then
        (sed -i '/%wheel ALL=(ALL) ALL/s/^#//' $CHROOT_MOUNT_POINT/etc/sudoers
                arch-chroot "$CHROOT_MOUNT_POINT" usermod -a -G wheel "$user") &> /dev/null &
        pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2usermod -a -G wheel $user\Zn" load
        fi
else
    while IFS= read -r i ; do
                 if [ "$(<<<"$i" cut -d: -f4)" == "" ]; then
                         arch-chroot "$CHROOT_MOUNT_POINT" useradd -m -G audio,network,power,storage,optical -s "$(<<<"$i" cut -d: -f2)" "$(<<<"$i" cut -d: -f1)" &>/dev/null &
                         pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2useradd $(<<<"$i" cut -d: -f1)\Zn" load
                 else
                         arch-chroot "$CHROOT_MOUNT_POINT" useradd -m -G audio,network,power,storage,optical -c "$(<<<"$i" cut -d: -f4)" -s "$(<<<"$i" cut -d: -f2)" "$(<<<"$i" cut -d: -f1)" &>/dev/null &
                         pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2useradd $(<<<"$i" cut -d: -f1)\Zn" load
                 fi

                 input="$(<<<"$i" cut -d: -f5 | openssl enc -aes-256-cbc -a -d -salt -pass pass:"$ssl_key")"
                 (printf "$input\n$input" | arch-chroot "$CHROOT_MOUNT_POINT" passwd "$(<<<"$i" cut -d: -f1)") &> /dev/null &
                 pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2passwd $(<<<"$i" cut -d: -f1)\Zn" load
                 unset input
                 echo "$(date -u "+%F %H:%M") : Password set: $(<<<"$i" cut -d: -f1)" >> "$log"

                 if [ "$(<<<"$i" cut -d: -f3)" == "yes" ]; then
                         (sed -i '/%wheel ALL=(ALL) ALL/s/^#//' $CHROOT_MOUNT_POINT/etc/sudoers
                         arch-chroot "$CHROOT_MOUNT_POINT" usermod -a -G wheel "$(<<<"$i" cut -d: -f1)") &> /dev/null &
             pid=$! pri=0.1 msg="$wait_load \n\n \Z1> \Z2usermod -a -G wheel $(<<<"$i" cut -d: -f1)\Zn" load
                 fi
    done <<<$(sort "$tmp_passwd")
fi