#!/usr/bin/env bash

local char=
local input=
local -a history=( )
local -i histindex=0
trap ctrl_c INT
working_dir=$(</tmp/chroot_dir.var)

while (true)
  do
    echo -n "${color_yellow}<${color_red}root${color_yellow}@${color_green}${CHOSEN_HOSTNAME}-chroot${color_yellow}>: $working_dir>${color_red}# ${color_none}" ; while IFS= read -r -n 1 -s char
      do
        if [ "${char}" == $'\x1b' ]; then
            while IFS= read -r -n 2 -s rest
              do
                char+="${rest}"
                break
            done
        fi

        if [ "${char}" == $'\x1b[D' ]; then
            pos=-1
        elif [ "${char}" == $'\x1b[C' ]; then
            pos=1
        elif [[ ${char} == $'\177' ]];  then
            input="${input%?}"
            echo -ne "\r\033[K${color_yellow}<${color_red}root${color_yellow}@${color_green}${CHOSEN_HOSTNAME}-chroot${color_yellow}>: ${working_dir}>${color_red}# ${color_none}${input}"
        ## User input up
        elif [ "${char}" == $'\x1b[A' ]; then
            if [ ${histindex} -gt 0 ]; then
                histindex+=-1
                input=$(echo -ne "${history[$histindex]}")
                echo -ne "\r\033[K${color_yellow}<${color_red}root${color_yellow}@${color_green}${CHOSEN_HOSTNAME}-chroot${color_yellow}>: ${working_dir}>${color_red}# ${color_none}${history[$histindex]}"
            fi
        ## User input down
            elif [ "${char}" == $'\x1b[B' ]; then
                    if [ ${histindex} -lt $((${#history[@]} - 1)) ]; then
                histindex+=1
                input=$(echo -ne "${history[$histindex]}")
                echo -ne "\r\033[K${color_yellow}<${color_red}root${color_yellow}@${color_green}${CHOSEN_HOSTNAME}-chroot${color_yellow}>: ${working_dir}>${color_red}# ${color_none}${history[$histindex]}"
            fi
        ### Newline
            elif [ -z "${char}" ]; then
            echo
                history+=( "${input}" )
                    histindex=${#history[@]}
            break
        else
            echo -n "${char}"
            input+="${char}"
        fi
    done

    if [ "${input}" == "anarchy" ] || [ "${input}" == "exit" ]; then
        rm /tmp/chroot_dir.var &> /dev/null
        clear
        break
    elif (<<<"${input}" grep "^cd " &> /dev/null); then
        ch_dir=$(<<<"${input}" cut -c4-)
        arch-chroot "${ARCH}" /bin/bash -c "cd ${working_dir} ; cd ${ch_dir} ; pwd > /etc/chroot_dir.var"
        mv "${ARCH}"/etc/chroot_dir.var /tmp/
        working_dir=$(</tmp/chroot_dir.var)
    elif  (<<<"${input}" grep "^help" &> /dev/null); then
        echo -e "${arch_chroot_msg}"
        else
        arch-chroot "${ARCH}" /bin/bash -c "cd ${working_dir} ; ${input}"
    fi
    input=
done
