#!/bin/sh

log "Checking for a network connection"

# Use netcat (nc) to check if we can connect to 1.1.1.1 on port 443
if nc -zw1 1.0.0.1 443; then
    log "Connected to the internet"
    exit 0
else
    log "Not connected to the internet"
    exit 1
fi