#!/usr/bin/env bash

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

log "Connecting to Wifi"

WIFI_INTERFACE="$(ip addr | grep "wlp\|wlo" | awk '{print $2}' | sed 's/://' | head -n 1)"

until "${has_internet_connection}"; do
    if [[ -n "${WIFI_INTERFACE}" ]]; then
        if (dialog --yes-button "${yes}" --no-button "${no}" --yesno "\n${wifi_msg0}" 10 60); then
            wifi-menu

            if [[ $? -gt 0 ]]; then
                dialog --ok-button "${ok}" --msgbox "\n${wifi_msg1}" 10 60
                log "Failed to connect to network"
                setterm -background black -store ; reset ; echo "${connect_err1}" | sed 's/\\Z1//;s/\\Zn//'
                exit 1
            else
                log "Connected to network ${WIFI_INTERFACE}"
                # TODO: Check if has_internet_connection can be local
                has_internet_connection=true
            fi
        else
            unset WIFI_INTERFACE
        fi
    else
        dialog --ok-button "${ok}" --msgbox "\n${connect_err0}" 10 60
        log "Failed to connect to network"
        setterm -background black -store ; reset ; echo -e "${connect_err1}" | sed 's/\\Z1//;s/\\Zn//'
        exit 1
    fi
done

return 0