#!/bin/sh

log "Connecting to wifi"

WIFI_INTERFACE="$(ip addr | grep "wlp\|wlo\|wlan" | awk '{print $2}' \
    | sed 's/://' | head -n 1)"
is_online="$(get_var 'is_online')"

log "Found wireless interface \'${WIFI_INTERFACE}\'"

until "${is_online}"; do
    if [ -n "${WIFI_INTERFACE}" ]; then
        if (dialog --yes-button "${yes}" --no-button "${no}" --yesno \
                "\n${wifi_msg0}" 10 60); then

            if wifi-menu -o; then
                dialog --ok-button "${ok}" --msgbox "\n${wifi_msg1}" 10 60
                log "Failed to connect to network"
                #setterm -background black -store ; reset ; echo "${connect_err1}" | sed 's/\\Z1//;s/\\Zn//'
                exit 1
            else
                log "Connected to network using \'${WIFI_INTERFACE}\'"
                set_var 'is_online' 'true'
            fi
        else
            unset WIFI_INTERFACE
        fi
    else
        dialog --ok-button "${ok}" --msgbox "\n${connect_err0}" 10 60
        log "Failed to connect to network"
        #setterm -background black -store ; reset ; echo -e "${connect_err1}" | sed 's/\\Z1//;s/\\Zn//'
        exit 1
    fi
done