#!/usr/bin/env bash

log "Connecting to wifi"

WIFI_INTERFACE="$(ip addr | grep "wlp\|wlo" | awk '{print $2}' | sed 's/://' | head -n 1)"
log "Found wireless interface \'${WIFI_INTERFACE}\'"

until "${has_internet_connection}"; do
    if [ -n "${WIFI_INTERFACE}" ]; then
        if (dialog --yes-button "${yes}" --no-button "${no}" --yesno "\n${wifi_msg0}" 10 60); then
            wifi-menu -o

            if [ $? -gt 0 ]; then
                dialog --ok-button "${ok}" --msgbox "\n${wifi_msg1}" 10 60
                log "Failed to connect to network"
                setterm -background black -store ; reset ; echo "${connect_err1}" | sed 's/\\Z1//;s/\\Zn//'
                exit 1
            else
                log "Connected to network using \'${WIFI_INTERFACE}\'"
                update_var 'has_internet_connection' 'true' || exit 42
            fi
        else
            unset WIFI_INTERFACE
        fi
    else
        dialog --ok-button "${ok}" --msgbox "\n${connect_err0}" 10 60
        log "Failed to connect to network"
        # Fix echo flags to be POSIX compliant
        setterm -background black -store ; reset ; echo -e "${connect_err1}" | sed 's/\\Z1//;s/\\Zn//'
        exit 1
    fi
done