#!/usr/bin/env bash
# Downloads and installs yay-bin from https://aur.archlinux.org/yay-bin.git

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

log "Installing yay-bin"

TMP_YAY_DIR="$(mktemp -d)"

# Install git as a dependency
pacman --noconfirm --quiet -Sy git

# Clone and install yay
git clone --quiet https://aur.archlinux.org/yay.git "${TMP_YAY_DIR}"
cd "${TMP_YAY_DIR}" || exit
makepkg --install --noconfirm &> /dev/null

log "Installed yay-bin"
return 0