#!/bin/sh
# Downloads and installs yay-bin from https://aur.archlinux.org/yay-bin.git

log "Installing yay-bin"

TMP_YAY_DIR="$(mktemp -d)"

# Install git as a dependency if needed
if command -v git; then
    pacman --noconfirm --quiet -Sy git > /dev/null
fi

# Clone and install yay
git clone --quiet https://aur.archlinux.org/yay.git "${TMP_YAY_DIR}/"
cd "${TMP_YAY_DIR}" || exit 1
makepkg --install --noconfirm > /dev/null || exit 2

log "Installed yay-bin"