#!/usr/bin/env bash

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

log "Entered main menu"

menu_title="${menu_op_msg}"

while (true); do
    menu_option="$(dialog --nocancel --ok-button "${ok}" --menu "${menu}" 19 60 8 \
        "${menu13}" "-" \
        "${menu0}"  "-" \
        "${menu1}"  "-" \
        "${menu2}"  "-" \
        "${menu3}"  "-" \
        "${menu5}"  "-" \
        "${menu11}" "-" \
        "${menu12}" "-" 3>&1 1>&2 2>&3)"

    log "Chose menu option: ${menu_option}"

    case "${menu_option}" in
        "${menu0}")
            run set-locale
        ;;

        "${menu1}")
            run set-timezone
        ;;
        "${menu2}")
            run set-keyboard-layout
        ;;

        # Return to partition menu
        "${menu3}")
            if "${mounted}"; then
                if (dialog --yes-button "${yes}" --no-button "${no}" --defaultno --yesno "\n${menu_err_msg3}" 10 60); then
                    mounted=false
                    export mounted
                    run prepare-disks
                fi
            else
                run prepare-disks
            fi
        ;;

        # Install base system
        "${menu5}")
            if "${mounted}"; then
                run choose-installation-options
                run set-hostname
                run set-user
                run choose-software
                run install-base
                run configure-system
                run add-user
                run reboot-menu
            elif (dialog --yes-button "${yes}" --no-button "${no}" --yesno "\n${install_err_msg1}" 10 60); then
                run prepare-disks
            fi
        ;;

        "${menu11}")
            run reboot-menu
        ;;

        # Exit without installing
        "${menu12}")
            if (dialog --yes-button "${yes}" --no-button "${no}" --yesno "\n${menu_exit_msg}" 10 60); then
                reset
                exit 0
            fi
        ;;

        # Enter the command line
        "${menu13}")
            echo -e "alias anarchy=exit ; echo -e '${return_msg}'" > /tmp/.zshrc
            clear
            ZDOTDIR=/tmp/ zsh
            rm /tmp/.zshrc
            clear
        ;;
    esac
done
