#!/usr/bin/env bash

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

log "Starting quick installation"

case "$1" in
    1)
        kernel="linux"
        sh="/usr/bin/zsh"
        shrc="${default}"
        bootloader="grub"
        net_util="networkmanager"
        enable_nm=true
        multilib=true
        dhcp=true
        desktop=true
        base_install=(
            'base-devel'
            'linux'
            'linux-headers'
            'zsh'
            'zsh-syntax-highlighting'
            'grub'
            'dialog'
            'networkmanager'
            'wireless_tools'
            'wpa_supplicant'
            'os-prober'
        )

        if "${install_bluetooth}" ; then
            base_install+=(
                'bluez'
                'bluez-utils'
                'pulseaudio-bluetooth'
            )
            enable_bt=true
        fi

        if "${enable_f2fs}" ; then
            base_install+=('f2fs-tools')
        fi

        if "${uefi}" ; then
            base_install+=('efibootmgr')
        fi

        # TODO: Fix reference
        run select_desktop.sh
        base_install+=("${DE}")
    ;;

    2)
        kernel="linux-lts"
        sh="/usr/bin/zsh"
        shrc="${default}"
        bootloader="grub"
        net_util="networkmanager"
        enable_nm=true
        multilib=true
        dhcp=true
        desktop=true
        base_install=(
            'base-devel'
            'linux-lts'
            'linux-lts-headers'
            'zsh'
            'zsh-syntax-highlighting'
            'grub'
            'dialog'
            'networkmanager'
            'wireless_tools'
            'wpa_supplicant'
            'os-prober'
        )

        if "${install_bluetooth}" ; then
            base_install+=(
                'bluez'
                'bluez-utils'
                'pulseaudio-bluetooth'
            )
            enable_bt=true
        fi

        if "${enable_f2fs}" ; then
             base_install+=('f2fs-tools')
        fi

        if "${uefi}" ; then
            base_install+=('efibootmgr')
        fi

        # TODO: Fix reference
        run select_desktop.sh
        base_install+=("${DE}")
    ;;

    3)
        kernel="linux"
        sh="/usr/bin/zsh"
        shrc="${default}"
        bootloader="grub"
        net_util="networkmanager"
        enable_nm=true
        multilib=true
        dhcp=true
        base_install=(
            'base-devel'
            'linux'
            'openssh'
            'linux-headers'
            'zsh'
            'zsh-syntax-highlighting'
            'grub'
            'dialog'
            'wireless_tools'
            'wpa_supplicant'
            'os-prober'
        )

        if "${install_bluetooth}" ; then
            base_install+=(
                'bluez'
                'bluez-utils'
                'pulseaudio-bluetooth'
            )
            enable_bt=true
        fi

        if "${enable_f2fs}" ; then
            base_install+=('f2fs-tools')
        fi

        if "${uefi}" ; then
            base_install+=('efibootmgr')
        fi
    ;;

    4)
        kernel="linux-lts"
        sh="/usr/bin/zsh"
        shrc="${default}"
        bootloader="grub"
        net_util="networkmanager"
        enable_nm=true
        multilib=true
        dhcp=true
        base_install=(
            'base-devel'
            'openssh'
            'linux-lts'
            'linux-lts-headers'
            'zsh'
            'zsh-syntax-highlighting'
            'grub'
            'dialog'
            'wireless_tools'
            'wpa_supplicant'
            'os-prober'
        )

        if "${install_bluetooth}" ; then
            base_install+=(
                'bluez'
                'bluez-utils'
                'pulseaudio-bluetooth'
            )
            enable_bt=true
        fi

        if "${enable_f2fs}" ; then
             base_install+=('f2fs-tools')
        fi

        if "${uefi}" ; then
            base_install+=('efibootmgr')
        fi
    ;;
esac

log "Adding quick install packages to package list"

# Append the selected packages to the packages file
for package in "${base_install[@]}"; do
    echo -e "${package}" >> "${ANARCHY_PACKAGES_FILE}"
done

log "Added quick install packages to package list"
return 0