#!/usr/bin/env bash

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

log "Entered reboot menu"

menu_title="${complete_op_msg}"

# Check if system was properly installed
if "${system_is_installed}"; then

    # Check if user has installed bootloader (otherwise unable to boot)
    if [[ "${bootloader}" == "false" ]]; then
        log "No bootloader installed"

        if (dialog --yes-button "${yes}" --no-button "${no}" --yesno "\n${complete_no_boot_msg}" 10 60); then
            log "Chose to exit the installer"
            reset
            exit 0
        fi
    fi

    while (true); do
        menu_option="$(dialog --nocancel --ok-button "${ok}" --menu "${complete_msg}" 16 60 7 \
            "${reboot0}" "-" \
            "${reboot6}" "-" \
            "${reboot2}" "-" \
            "${reboot1}" "-" \
            "${reboot4}" "-" \
            "${reboot3}" "-" \
            "${reboot5}" "-" 3>&1 1>&2 2>&3)"

        case "${reboot_menu}" in

            # Reboot system
            "${reboot0}")
                umount -R "${CHROOT_MOUNT_POINT}"
                reset
                reboot
                exit 0
            ;;

            # Shut down system
            "${reboot6}")
                umount -R "${CHROOT_MOUNT_POINT}"
                reset
                poweroff
                exit 0
            ;;

            # Return to command prompt
            "${reboot1}")
                umount -R "${CHROOT_MOUNT_POINT}"
                reset
                exit 0
            ;;

            # Enter chroot
            "${reboot2}")
                clear
                echo -e "${arch_chroot_msg}"
                echo "/root" > /tmp/chroot_dir.var
                run anarchy-chroot
                clear
            ;;

            # Edit users
            "${reboot3}")
                menu_enter=true
                export menu_enter
                run set-user
            ;;

            # Install additional software
            "${reboot5}")
                menu_enter=true
                export menu_enter
                run choose-software
            ;;

            # Show installation log (in less)
            "${reboot4}")
                clear
                less "${LOG_FILE}"
                clear
            ;;
        esac
    done
else
    # System was not installed properly
    if (dialog --yes-button "${yes}" --no-button "${no}" --yesno "${not_complete_msg}" 10 60); then
        umount -R "${CHROOT_MOUNT_POINT}"
        reset
        reboot
        exit 0
    fi
fi
