#!/bin/sh

log "Started keyboard layout selection"

menu_title="${key_op_msg}"

KEYMAPS_LIST="$(find /usr/share/kbd/keymaps -type f | sed -n -e 's!^.*/!!p' \
    | grep ".map.gz" | sed 's/.map.gz//g' | sed 's/$/ -/g' | sort)"

while (true); do
    keyboard_layout="$(dialog --nocancel --ok-button "${ok}" \
        --menu "${keys_msg}" 18 60 10 \
    "us"        "United States" \
    "de"        "German" \
    "el"        "Greek" \
    "hu"        "Hungarian" \
    "es"        "Spanish" \
    "fr"        "French" \
    "it"        "Italian" \
    "pt-latin9" "Portugal" \
    "ro"        "Romanian" \
    "ru"        "Russian" \
    "sl"        "Slovenian" \
    "sv"        "Swedish" \
    "uk"        "United Kingdom" \
    "${other}"  "${other-keymaps}" 3>&1 1>&2 2>&3)"

    if [ "${keyboard_layout}" = "${other}" ]; then
        keyboard_layout="$(dialog --ok-button "${ok}" \
            --cancel-button "${cancel}" --menu "${keys_msg}" 19 60 10 \
            "${KEYMAPS_LIST}" 3>&1 1>&2 2>&3)"

        if [ $? -eq 0 ]; then
            break
        fi
    else
        break
    fi
done

log "Selected keyboard layout: \'${keyboard_layout}\'"
localectl set-keymap "${keyboard_layout}" > /dev/null
exit $?