#!/usr/bin/env bash

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_PATH}"/*.sh; do
    source "${library}"
done

log "Setting password"

menu_title="${passwd_op_msg}"

SSL_KEY="$(openssl rand -base64 32)"

while [[ "${PASSWORD}" != "${input_chk}" ]]; do
    # TODO: Check if we can enable secure password input
    PASSWORD="$(dialog --nocancel --clear --insecure --passwordbox "${user_var0}" 11 55 --stdout)"
    PASSWORD_CHECK="$(dialog --nocancel --clear --insecure --passwordbox "${user_var1}" 11 55 --stdout)"

    if [[ -z "${PASSWORD}" ]]; then
        dialog --ok-button "${ok}" --msgbox "\n${passwd_msg0}" 10 55
        PASSWORD_CHECK=default
    elif [[ "${PASSWORD}" != "${PASSWORD_CHECK}" ]]; then
        dialog --ok-button "${ok}" --msgbox "\n${passwd_msg1}" 10 55
    fi
done

ENCRYPTED_PASSWORD="$(echo "${PASSWORD}" | openssl enc -aes-256-cbc -a -salt -pass pass:"${SSL_KEY}")"
sleep 1 &
pid=$!
pri=0.1
msg="${wait_load} \n\n \Z1> \Z2encrypt passwd\Zn"

# Call load with the variables
load "${pid}" "${pri}" "${msg}"

unset PASSWORD PASSWORD_CHECK ; PASSWORD_CHECK=default

log "Successfully set password"

export ENCRYPTED_PASSWORD
export SSL_KEY

exit 0