#!/usr/bin/env bash

# Source config file and libraries
source "${ANARCHY_CONFIG_FILE}"
for library in "${ANARCHY_LIBRARIES_DIRECTORY}"/*.sh; do
    source "${library}"
done

log "Testing connection"

menu_title="${connection_op_msg}"

TMP_DIR="$(mktemp -d)"

(test_mirror=$(</etc/pacman.d/mirrorlist grep "^Server" | awk 'NR==1{print $3}' | sed 's/$.*//')
test_pkg=$(curl -s https://www.archlinux.org/packages/extra/x86_64/bluez-utils/ | grep "<title>" | awk '{print $4"-"$5}')
test_link="${test_mirror}extra/os/x86_64/${test_pkg}-x86_64.pkg.tar.xz"
wget -4 --no-check-certificate --append-output="${TMP_DIR}"/wget.log -O /dev/null "${test_link}") &
pid=$! pri=0.3 msg="\n${connection_load} \n\n \Z1> \Z2wget -O /dev/null test_link/test1Mb.db\Zn" load

sed -i 's/\,/\./' "${TMP_DIR}"/wget.log
connection_speed=$(tail "${TMP_DIR}"/wget.log | grep -oP '(?<=\().*(?=\))' | awk '{print $1}')
connection_rate=$(tail "${TMP_DIR}"/wget.log | grep -oP '(?<=\().*(?=\))' | awk '{print $2}')

if (lscpu | grep "max MHz" &>/dev/null); then
    cpu_mhz=$(lscpu | grep "CPU max MHz" | awk '{print $4}' | sed 's/\..*//')
else
    cpu_mhz=$(lscpu | grep "CPU MHz" | awk '{print $3}' | sed 's/\..*//')
fi

case "${cpu_mhz}" in
    [0-9][0-9][0-9])
        cpu_sleep=4.5
    ;;
    [1][0-9][0-9][0-9])
        cpu_sleep=4
    ;;
    [2][0-9][0-9][0-9])
        cpu_sleep=3.5
    ;;
    *)
        cpu_sleep=2.5
    ;;
esac

# TODO: Check if the exports are even needed
export connection_speed
export connection_rate
export cpu_sleep

log "Connection speed: ${connection_speed} ${connection_rate}"
log "CPU speed (MHz): ${cpu_mhz}"

rm "${TMP_DIR}"/wget.log &> /dev/null
return 0