#!/bin/sh

log "Updating mirrorlist"

menu_title="${mirror_op_msg}"

while (true); do
    edit_mirrors="$(dialog --ok-button "${ok}" \
        --menu "\n${mirror_msg0}\n" 12 60 3 \
        "${update_mirrors_msg}" "->" \
        "${manual_mirrors}" "->" \
        "${cancel_mirrors}" "->" 3>&1 1>&2 2>&3)"

    if [ $? -gt 0 ] || [ "${edit_mirrors}" = "${cancel_mirrors}" ]; then
        if (dialog --yes-button "${yes}" --no-button "${no}" \
                --yesno "\n${mirror_cancel_msg}" 10 60); then
            log "Didn't update mirrorlist"
            exit 0
        fi
    fi

    case "${edit_mirrors}" in
        "${update_mirrors_msg}")
            log "Updating mirrorlist with reflector"
            reflector --sort rate --fastest 20 --latest 20 --number 10 \
                --save /etc/pacman.d/mirrorlist
        ;;

        "${manual_mirrors}")
            log "Manually updating mirrorlist"
            EDITOR="$(dialog --ok-button "${ok}" --menu "${mirror_editor_msg}" \
                10 60 3 \
                "nano"  "${nano_msg}" \
                "vim"   "${vim_msg}" \
                "${cancel}" "->" 3>&1 1>&2 2>&3)"

            if [ $? -gt 0 ] || [ "${EDITOR}" = "${cancel}" ]; then
                if (dialog --yes-button "${yes}" --no-button "${no}" \
                        --yesno "\n${mirror_cancel_msg}" 10 60); then
                    break
                fi
            else
                "${EDITOR}" /etc/pacman.d/mirrorlist
                log "Updated mirrorlist with ${EDITOR}"
                break
            fi
        ;;
    esac
done